//
//  Countries.swift
//  FlaggIt!
//
//  Created by Marius on 07.07.26.
//

import Foundation
import SwiftUI
enum Region: String, CaseIterable {
    case europe = "Europa"
    case asia = "Asien"
    case africa = "Afrika"
    case americas = "Amerika"
    case oceania = "Ozeanien"
    case antarctica = "Antarktis"
    case all = "Alle"
}

extension Region: Identifiable {
    var id: Self {self}
}

extension Color {
    static let appBackground = Color(light: Color(red: 0.96, green: 0.95, blue: 0.93),
                                       dark: Color(red: 0.09, green: 0.09, blue: 0.10))
    static let appCard = Color(light: .white,
                                 dark: Color(red: 0.15, green: 0.15, blue: 0.16))
    static let appAccent = Color(red: 0.85, green: 0.42, blue: 0.20) // warmes Terracotta/Orange
    static let appTextPrimary = Color(light: Color(red: 0.12, green: 0.12, blue: 0.13),
                                        dark: .white)
    static let appTextSecondary = Color(light: .gray, dark: Color(white: 0.65))
}

// Hilfsinitializer für Light/Dark
extension Color {
    init(light: Color, dark: Color) {
        self = Color(UIColor { trait in
            trait.userInterfaceStyle == .dark ? UIColor(dark) : UIColor(light)
        })
    }
}

struct Country: Identifiable, Hashable {
    let id: String
    let assetName: String
    let isoCode: String
    let region: Region

    var localizedName: String {
        Locale.current.localizedString(forRegionCode: isoCode) ?? assetName
    }
}

extension Country {
    static let all: [Country] = [
        Country(id: "AF", assetName: "Afghanistan", isoCode: "AF", region: .asia),
        Country(id: "AX", assetName: "AlandIslands", isoCode: "AX", region: .europe),
        Country(id: "AL", assetName: "Albania", isoCode: "AL", region: .europe),
        Country(id: "DZ", assetName: "Algeria", isoCode: "DZ", region: .africa),
        Country(id: "AS", assetName: "AmericanSamoa", isoCode: "AS", region: .oceania),
        Country(id: "AD", assetName: "Andorra", isoCode: "AD", region: .europe),
        Country(id: "AO", assetName: "Angola", isoCode: "AO", region: .africa),
        Country(id: "AI", assetName: "Anguilla", isoCode: "AI", region: .americas),
        Country(id: "AQ", assetName: "Antarctica", isoCode: "AQ", region: .antarctica),
        Country(id: "AG", assetName: "AntiguaandBarbuda", isoCode: "AG", region: .americas),
        Country(id: "AR", assetName: "Argentina", isoCode: "AR", region: .americas),
        Country(id: "AM", assetName: "Armenia", isoCode: "AM", region: .asia),
        Country(id: "AW", assetName: "Aruba", isoCode: "AW", region: .americas),
        Country(id: "AU", assetName: "Australia", isoCode: "AU", region: .oceania),
        Country(id: "AT", assetName: "Austria", isoCode: "AT", region: .europe),
        Country(id: "AZ", assetName: "Azerbaijan", isoCode: "AZ", region: .asia),
        Country(id: "BS", assetName: "Bahamas", isoCode: "BS", region: .americas),
        Country(id: "BH", assetName: "Bahrain", isoCode: "BH", region: .asia),
        Country(id: "BD", assetName: "Bangladesh", isoCode: "BD", region: .asia),
        Country(id: "BB", assetName: "Barbados", isoCode: "BB", region: .americas),
        Country(id: "BY", assetName: "Belarus", isoCode: "BY", region: .europe),
        Country(id: "BE", assetName: "Belgium", isoCode: "BE", region: .europe),
        Country(id: "BZ", assetName: "Belize", isoCode: "BZ", region: .americas),
        Country(id: "BJ", assetName: "Benin", isoCode: "BJ", region: .africa),
        Country(id: "BM", assetName: "Bermuda", isoCode: "BM", region: .americas),
        Country(id: "BT", assetName: "Bhutan", isoCode: "BT", region: .asia),
        Country(id: "BO", assetName: "BoliviaPlurinationalStateof", isoCode: "BO", region: .americas),
        Country(id: "BQ", assetName: "BonaireSintEustatiusandSaba", isoCode: "BQ", region: .americas),
        Country(id: "BA", assetName: "BosniaandHerzegovina", isoCode: "BA", region: .europe),
        Country(id: "BW", assetName: "Botswana", isoCode: "BW", region: .africa),
        Country(id: "BV", assetName: "BouvetIsland", isoCode: "BV", region: .antarctica),
        Country(id: "BR", assetName: "Brazil", isoCode: "BR", region: .americas),
        Country(id: "IO", assetName: "BritishIndianOceanTerritory", isoCode: "IO", region: .asia),
        Country(id: "BN", assetName: "BruneiDarussalam", isoCode: "BN", region: .asia),
        Country(id: "BG", assetName: "Bulgaria", isoCode: "BG", region: .europe),
        Country(id: "BF", assetName: "BurkinaFaso", isoCode: "BF", region: .africa),
        Country(id: "BI", assetName: "Burundi", isoCode: "BI", region: .africa),
        Country(id: "CV", assetName: "CaboVerde", isoCode: "CV", region: .africa),
        Country(id: "KH", assetName: "Cambodia", isoCode: "KH", region: .asia),
        Country(id: "CM", assetName: "Cameroon", isoCode: "CM", region: .africa),
        Country(id: "CA", assetName: "Canada", isoCode: "CA", region: .americas),
        Country(id: "KY", assetName: "CaymanIslands", isoCode: "KY", region: .americas),
        Country(id: "CF", assetName: "CentralAfricanRepublic", isoCode: "CF", region: .africa),
        Country(id: "TD", assetName: "Chad", isoCode: "TD", region: .africa),
        Country(id: "CL", assetName: "Chile", isoCode: "CL", region: .americas),
        Country(id: "CN", assetName: "China", isoCode: "CN", region: .asia),
        Country(id: "CX", assetName: "ChristmasIsland", isoCode: "CX", region: .asia),
        Country(id: "CC", assetName: "CocosKeelingIslands", isoCode: "CC", region: .asia),
        Country(id: "CO", assetName: "Colombia", isoCode: "CO", region: .americas),
        Country(id: "KM", assetName: "Comoros", isoCode: "KM", region: .africa),
        Country(id: "CG", assetName: "Congo", isoCode: "CG", region: .africa),
        Country(id: "CD", assetName: "CongoTheDemocraticRepublicofthe", isoCode: "CD", region: .africa),
        Country(id: "CK", assetName: "CookIslands", isoCode: "CK", region: .oceania),
        Country(id: "CR", assetName: "CostaRica", isoCode: "CR", region: .americas),
        Country(id: "CI", assetName: "CotedIvoire", isoCode: "CI", region: .africa),
        Country(id: "HR", assetName: "Croatia", isoCode: "HR", region: .europe),
        Country(id: "CU", assetName: "Cuba", isoCode: "CU", region: .americas),
        Country(id: "CW", assetName: "Curacao", isoCode: "CW", region: .americas),
        Country(id: "CY", assetName: "Cyprus", isoCode: "CY", region: .asia),
        Country(id: "CZ", assetName: "Czechia", isoCode: "CZ", region: .europe),
        Country(id: "DK", assetName: "Denmark", isoCode: "DK", region: .europe),
        Country(id: "DJ", assetName: "Djibouti", isoCode: "DJ", region: .africa),
        Country(id: "DM", assetName: "Dominica", isoCode: "DM", region: .americas),
        Country(id: "DO", assetName: "DominicanRepublic", isoCode: "DO", region: .americas),
        Country(id: "EC", assetName: "Ecuador", isoCode: "EC", region: .americas),
        Country(id: "EG", assetName: "Egypt", isoCode: "EG", region: .africa),
        Country(id: "SV", assetName: "ElSalvador", isoCode: "SV", region: .americas),
        Country(id: "GQ", assetName: "EquatorialGuinea", isoCode: "GQ", region: .africa),
        Country(id: "ER", assetName: "Eritrea", isoCode: "ER", region: .africa),
        Country(id: "EE", assetName: "Estonia", isoCode: "EE", region: .europe),
        Country(id: "SZ", assetName: "Eswatini", isoCode: "SZ", region: .africa),
        Country(id: "ET", assetName: "Ethiopia", isoCode: "ET", region: .africa),
        Country(id: "FK", assetName: "FalklandIslandsMalvinas", isoCode: "FK", region: .americas),
        Country(id: "FO", assetName: "FaroeIslands", isoCode: "FO", region: .europe),
        Country(id: "FJ", assetName: "Fiji", isoCode: "FJ", region: .oceania),
        Country(id: "FI", assetName: "Finland", isoCode: "FI", region: .europe),
        Country(id: "FR", assetName: "France", isoCode: "FR", region: .europe),
        Country(id: "GF", assetName: "FrenchGuiana", isoCode: "GF", region: .americas),
        Country(id: "PF", assetName: "FrenchPolynesia", isoCode: "PF", region: .oceania),
        Country(id: "TF", assetName: "FrenchSouthernTerritories", isoCode: "TF", region: .africa),
        Country(id: "GA", assetName: "Gabon", isoCode: "GA", region: .africa),
        Country(id: "GM", assetName: "Gambia", isoCode: "GM", region: .africa),
        Country(id: "GE", assetName: "Georgia", isoCode: "GE", region: .asia),
        Country(id: "DE", assetName: "Germany", isoCode: "DE", region: .europe),
        Country(id: "GH", assetName: "Ghana", isoCode: "GH", region: .africa),
        Country(id: "GI", assetName: "Gibraltar", isoCode: "GI", region: .europe),
        Country(id: "GR", assetName: "Greece", isoCode: "GR", region: .europe),
        Country(id: "GL", assetName: "Greenland", isoCode: "GL", region: .americas),
        Country(id: "GD", assetName: "Grenada", isoCode: "GD", region: .americas),
        Country(id: "GP", assetName: "Guadeloupe", isoCode: "GP", region: .americas),
        Country(id: "GU", assetName: "Guam", isoCode: "GU", region: .oceania),
        Country(id: "GT", assetName: "Guatemala", isoCode: "GT", region: .americas),
        Country(id: "GG", assetName: "Guernsey", isoCode: "GG", region: .europe),
        Country(id: "GN", assetName: "Guinea", isoCode: "GN", region: .africa),
        Country(id: "GW", assetName: "GuineaBissau", isoCode: "GW", region: .africa),
        Country(id: "GY", assetName: "Guyana", isoCode: "GY", region: .americas),
        Country(id: "HT", assetName: "Haiti", isoCode: "HT", region: .americas),
        Country(id: "HM", assetName: "HeardIslandandMcDonaldIslands", isoCode: "HM", region: .oceania),
        Country(id: "VA", assetName: "HolySeeVaticanCityState", isoCode: "VA", region: .europe),
        Country(id: "HN", assetName: "Honduras", isoCode: "HN", region: .americas),
        Country(id: "HK", assetName: "HongKong", isoCode: "HK", region: .asia),
        Country(id: "HU", assetName: "Hungary", isoCode: "HU", region: .europe),
        Country(id: "IS", assetName: "Iceland", isoCode: "IS", region: .europe),
        Country(id: "IN", assetName: "India", isoCode: "IN", region: .asia),
        Country(id: "ID", assetName: "Indonesia", isoCode: "ID", region: .asia),
        Country(id: "IR", assetName: "IranIslamicRepublicof", isoCode: "IR", region: .asia),
        Country(id: "IQ", assetName: "Iraq", isoCode: "IQ", region: .asia),
        Country(id: "IE", assetName: "Ireland", isoCode: "IE", region: .europe),
        Country(id: "IM", assetName: "IsleofMan", isoCode: "IM", region: .europe),
        Country(id: "IL", assetName: "Israel", isoCode: "IL", region: .asia),
        Country(id: "IT", assetName: "Italy", isoCode: "IT", region: .europe),
        Country(id: "JM", assetName: "Jamaica", isoCode: "JM", region: .americas),
        Country(id: "JP", assetName: "Japan", isoCode: "JP", region: .asia),
        Country(id: "JE", assetName: "Jersey", isoCode: "JE", region: .europe),
        Country(id: "JO", assetName: "Jordan", isoCode: "JO", region: .asia),
        Country(id: "KZ", assetName: "Kazakhstan", isoCode: "KZ", region: .asia),
        Country(id: "KE", assetName: "Kenya", isoCode: "KE", region: .africa),
        Country(id: "KI", assetName: "Kiribati", isoCode: "KI", region: .oceania),
        Country(id: "KP", assetName: "KoreaDemocraticPeoplesRepublicof", isoCode: "KP", region: .asia),
        Country(id: "KR", assetName: "KoreaRepublicof", isoCode: "KR", region: .asia),
        Country(id: "XK", assetName: "Kosovo", isoCode: "XK", region: .europe),
        Country(id: "KW", assetName: "Kuwait", isoCode: "KW", region: .asia),
        Country(id: "KG", assetName: "Kyrgyzstan", isoCode: "KG", region: .asia),
        Country(id: "LA", assetName: "LaoPeoplesDemocraticRepublic", isoCode: "LA", region: .asia),
        Country(id: "LV", assetName: "Latvia", isoCode: "LV", region: .europe),
        Country(id: "LB", assetName: "Lebanon", isoCode: "LB", region: .asia),
        Country(id: "LS", assetName: "Lesotho", isoCode: "LS", region: .africa),
        Country(id: "LR", assetName: "Liberia", isoCode: "LR", region: .africa),
        Country(id: "LY", assetName: "Libya", isoCode: "LY", region: .africa),
        Country(id: "LI", assetName: "Liechtenstein", isoCode: "LI", region: .europe),
        Country(id: "LT", assetName: "Lithuania", isoCode: "LT", region: .europe),
        Country(id: "LU", assetName: "Luxembourg", isoCode: "LU", region: .europe),
        Country(id: "MO", assetName: "Macao", isoCode: "MO", region: .asia),
        Country(id: "MG", assetName: "Madagascar", isoCode: "MG", region: .africa),
        Country(id: "MW", assetName: "Malawi", isoCode: "MW", region: .africa),
        Country(id: "MY", assetName: "Malaysia", isoCode: "MY", region: .asia),
        Country(id: "MV", assetName: "Maldives", isoCode: "MV", region: .asia),
        Country(id: "ML", assetName: "Mali", isoCode: "ML", region: .africa),
        Country(id: "MT", assetName: "Malta", isoCode: "MT", region: .europe),
        Country(id: "MH", assetName: "MarshallIslands", isoCode: "MH", region: .oceania),
        Country(id: "MQ", assetName: "Martinique", isoCode: "MQ", region: .americas),
        Country(id: "MR", assetName: "Mauritania", isoCode: "MR", region: .africa),
        Country(id: "MU", assetName: "Mauritius", isoCode: "MU", region: .africa),
        Country(id: "YT", assetName: "Mayotte", isoCode: "YT", region: .africa),
        Country(id: "MX", assetName: "Mexico", isoCode: "MX", region: .americas),
        Country(id: "FM", assetName: "MicronesiaFederatedStatesof", isoCode: "FM", region: .oceania),
        Country(id: "MD", assetName: "MoldovaRepublicof", isoCode: "MD", region: .europe),
        Country(id: "MC", assetName: "Monaco", isoCode: "MC", region: .europe),
        Country(id: "MN", assetName: "Mongolia", isoCode: "MN", region: .asia),
        Country(id: "ME", assetName: "Montenegro", isoCode: "ME", region: .europe),
        Country(id: "MS", assetName: "Montserrat", isoCode: "MS", region: .americas),
        Country(id: "MA", assetName: "Morocco", isoCode: "MA", region: .africa),
        Country(id: "MZ", assetName: "Mozambique", isoCode: "MZ", region: .africa),
        Country(id: "MM", assetName: "Myanmar", isoCode: "MM", region: .asia),
        Country(id: "NA", assetName: "Namibia", isoCode: "NA", region: .africa),
        Country(id: "NR", assetName: "Nauru", isoCode: "NR", region: .oceania),
        Country(id: "NP", assetName: "Nepal", isoCode: "NP", region: .asia),
        Country(id: "NL", assetName: "Netherlands", isoCode: "NL", region: .europe),
        Country(id: "NC", assetName: "NewCaledonia", isoCode: "NC", region: .oceania),
        Country(id: "NZ", assetName: "NewZealand", isoCode: "NZ", region: .oceania),
        Country(id: "NI", assetName: "Nicaragua", isoCode: "NI", region: .americas),
        Country(id: "NE", assetName: "Niger", isoCode: "NE", region: .africa),
        Country(id: "NG", assetName: "Nigeria", isoCode: "NG", region: .africa),
        Country(id: "NU", assetName: "Niue", isoCode: "NU", region: .oceania),
        Country(id: "NF", assetName: "NorfolkIsland", isoCode: "NF", region: .oceania),
        Country(id: "MK", assetName: "NorthMacedonia", isoCode: "MK", region: .europe),
        Country(id: "MP", assetName: "NorthernMarianaIslands", isoCode: "MP", region: .oceania),
        Country(id: "NO", assetName: "Norway", isoCode: "NO", region: .europe),
        Country(id: "OM", assetName: "Oman", isoCode: "OM", region: .asia),
        Country(id: "PK", assetName: "Pakistan", isoCode: "PK", region: .asia),
        Country(id: "PW", assetName: "Palau", isoCode: "PW", region: .oceania),
        Country(id: "PS", assetName: "PalestineStateof", isoCode: "PS", region: .asia),
        Country(id: "PA", assetName: "Panama", isoCode: "PA", region: .americas),
        Country(id: "PG", assetName: "PapuaNewGuinea", isoCode: "PG", region: .oceania),
        Country(id: "PY", assetName: "Paraguay", isoCode: "PY", region: .americas),
        Country(id: "PE", assetName: "Peru", isoCode: "PE", region: .americas),
        Country(id: "PH", assetName: "Philippines", isoCode: "PH", region: .asia),
        Country(id: "PN", assetName: "Pitcairn", isoCode: "PN", region: .oceania),
        Country(id: "PL", assetName: "Poland", isoCode: "PL", region: .europe),
        Country(id: "PT", assetName: "Portugal", isoCode: "PT", region: .europe),
        Country(id: "PR", assetName: "PuertoRico", isoCode: "PR", region: .americas),
        Country(id: "QA", assetName: "Qatar", isoCode: "QA", region: .asia),
        Country(id: "RE", assetName: "Reunion", isoCode: "RE", region: .africa),
        Country(id: "RO", assetName: "Romania", isoCode: "RO", region: .europe),
        Country(id: "RU", assetName: "RussianFederation", isoCode: "RU", region: .europe),
        Country(id: "RW", assetName: "Rwanda", isoCode: "RW", region: .africa),
        Country(id: "BL", assetName: "SaintBarthelemy", isoCode: "BL", region: .americas),
        Country(id: "SH", assetName: "SaintHelenaAscensionandTristandaCunha", isoCode: "SH", region: .africa),
        Country(id: "KN", assetName: "SaintKittsandNevis", isoCode: "KN", region: .americas),
        Country(id: "LC", assetName: "SaintLucia", isoCode: "LC", region: .americas),
        Country(id: "MF", assetName: "SaintMartinFrenchpart", isoCode: "MF", region: .americas),
        Country(id: "PM", assetName: "SaintPierreandMiquelon", isoCode: "PM", region: .americas),
        Country(id: "VC", assetName: "SaintVincentandtheGrenadines", isoCode: "VC", region: .americas),
        Country(id: "WS", assetName: "Samoa", isoCode: "WS", region: .oceania),
        Country(id: "SM", assetName: "SanMarino", isoCode: "SM", region: .europe),
        Country(id: "ST", assetName: "SaoTomeandPrincipe", isoCode: "ST", region: .africa),
        Country(id: "SA", assetName: "SaudiArabia", isoCode: "SA", region: .asia),
        Country(id: "SN", assetName: "Senegal", isoCode: "SN", region: .africa),
        Country(id: "RS", assetName: "Serbia", isoCode: "RS", region: .europe),
        Country(id: "SC", assetName: "Seychelles", isoCode: "SC", region: .africa),
        Country(id: "SL", assetName: "SierraLeone", isoCode: "SL", region: .africa),
        Country(id: "SG", assetName: "Singapore", isoCode: "SG", region: .asia),
        Country(id: "SX", assetName: "SintMaartenDutchpart", isoCode: "SX", region: .americas),
        Country(id: "SK", assetName: "Slovakia", isoCode: "SK", region: .europe),
        Country(id: "SI", assetName: "Slovenia", isoCode: "SI", region: .europe),
        Country(id: "SB", assetName: "SolomonIslands", isoCode: "SB", region: .oceania),
        Country(id: "SO", assetName: "Somalia", isoCode: "SO", region: .africa),
        Country(id: "ZA", assetName: "SouthAfrica", isoCode: "ZA", region: .africa),
        Country(id: "GS", assetName: "SouthGeorgiaandtheSouthSandwichIslands", isoCode: "GS", region: .antarctica),
        Country(id: "SS", assetName: "SouthSudan", isoCode: "SS", region: .africa),
        Country(id: "ES", assetName: "Spain", isoCode: "ES", region: .europe),
        Country(id: "LK", assetName: "SriLanka", isoCode: "LK", region: .asia),
        Country(id: "SD", assetName: "Sudan", isoCode: "SD", region: .africa),
        Country(id: "SR", assetName: "Suriname", isoCode: "SR", region: .americas),
        Country(id: "SJ", assetName: "SvalbardandJanMayen", isoCode: "SJ", region: .europe),
        Country(id: "SE", assetName: "Sweden", isoCode: "SE", region: .europe),
        Country(id: "CH", assetName: "Switzerland", isoCode: "CH", region: .europe),
        Country(id: "SY", assetName: "SyrianArabRepublic", isoCode: "SY", region: .asia),
        Country(id: "TW", assetName: "TaiwanProvinceofChina", isoCode: "TW", region: .asia),
        Country(id: "TJ", assetName: "Tajikistan", isoCode: "TJ", region: .asia),
        Country(id: "TZ", assetName: "TanzaniaUnitedRepublicof", isoCode: "TZ", region: .africa),
        Country(id: "TH", assetName: "Thailand", isoCode: "TH", region: .asia),
        Country(id: "TL", assetName: "TimorLeste", isoCode: "TL", region: .asia),
        Country(id: "TG", assetName: "Togo", isoCode: "TG", region: .africa),
        Country(id: "TK", assetName: "Tokelau", isoCode: "TK", region: .oceania),
        Country(id: "TO", assetName: "Tonga", isoCode: "TO", region: .oceania),
        Country(id: "TT", assetName: "TrinidadandTobago", isoCode: "TT", region: .americas),
        Country(id: "TN", assetName: "Tunisia", isoCode: "TN", region: .africa),
        Country(id: "TR", assetName: "Turkiye", isoCode: "TR", region: .asia),
        Country(id: "TM", assetName: "Turkmenistan", isoCode: "TM", region: .asia),
        Country(id: "TC", assetName: "TurksandCaicosIslands", isoCode: "TC", region: .americas),
        Country(id: "TV", assetName: "Tuvalu", isoCode: "TV", region: .oceania),
        Country(id: "GB", assetName: "UK", isoCode: "GB", region: .europe),
        Country(id: "US", assetName: "US", isoCode: "US", region: .americas),
        Country(id: "UG", assetName: "Uganda", isoCode: "UG", region: .africa),
        Country(id: "UA", assetName: "Ukraine", isoCode: "UA", region: .europe),
        Country(id: "AE", assetName: "UnitedArabEmirates", isoCode: "AE", region: .asia),
        Country(id: "UM", assetName: "UnitedStatesMinorOutlyingIslands", isoCode: "UM", region: .oceania),
        Country(id: "UY", assetName: "Uruguay", isoCode: "UY", region: .americas),
        Country(id: "UZ", assetName: "Uzbekistan", isoCode: "UZ", region: .asia),
        Country(id: "VU", assetName: "Vanuatu", isoCode: "VU", region: .oceania),
        Country(id: "VE", assetName: "VenezuelaBolivarianRepublicof", isoCode: "VE", region: .americas),
        Country(id: "VN", assetName: "VietNam", isoCode: "VN", region: .asia),
        Country(id: "VG", assetName: "VirginIslandsBritish", isoCode: "VG", region: .americas),
        Country(id: "VI", assetName: "VirginIslandsUS", isoCode: "VI", region: .americas),
        Country(id: "WF", assetName: "WallisandFutuna", isoCode: "WF", region: .oceania),
        Country(id: "EH", assetName: "WesternSahara", isoCode: "EH", region: .africa),
        Country(id: "YE", assetName: "Yemen", isoCode: "YE", region: .asia),
        Country(id: "ZM", assetName: "Zambia", isoCode: "ZM", region: .africa),
        Country(id: "ZW", assetName: "Zimbabwe", isoCode: "ZW", region: .africa),
    ]
}
